:sparkles: feat: Add footer with correct styling
kahenya-anita/Bumble-Clone pull request #3
Opened 2023-02-15 14:17 UTC by kahenya-anita

Footer

2023-02-15 14:17 UTC, kahenya-anita commented
Task linked: [CU-8669fja8v Footer](https://app.clickup.com/t/8669fja8v)

2023-03-01 14:12 UTC, HenryMoringa commented on Footer/footer.html
> +        <div class="links-items">
Either use a div with role of list or preferably use a list element instead

2023-03-01 14:16 UTC, HenryMoringa commented on Footer/footer.html
> +            <div class="link-top">
Change this into a list item

2023-03-01 14:21 UTC, HenryMoringa commented
- Change the name to conform to agreed upon standard

2023-03-01 14:21 UTC, HenryMoringa requested changes

2023-03-01 14:21 UTC, HenryMoringa commented on Footer/footer.html
> +                <div class="links"><a href="#">Events</a></div>
Remove unnecessary divs

2023-03-12 16:58 UTC, closed without merging