create: add navbar and the homepage
kahenya-anita/Bumble-Clone pull request #5
Opened 2023-03-01 13:52 UTC by hamida-mstafa

2023-03-01 14:23 UTC, HenryMoringa requested changes

2023-03-01 14:23 UTC, HenryMoringa commented on nav.html
> +            <div class="nav">
This is unneccessary

2023-05-28 10:49 UTC, hamida-mstafa commented
## Description
Added class names to factor in BEM methodology for easy styling.

## Types Of Changes
[] Bug fix

[] New Feature

[] Breaking Changes

## Checklist:
[x]My code follows the code style of this project

[x]All new and existing tests passed.

[x]My code has been lined and formatted correctly.

[x]I have commented on my code, particularly in hard-to-understand areas.

[x]My changes generate no new warnings.

2023-06-16 09:03 UTC, kahenya-anita approved these changes

2023-06-16 09:04 UTC, merged